### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by CsatiZoltan** [JimHokanson/plotBig_Matlab#15]
How can I create the necessary mex files? I used `big_plot.compile`, but it stopped at this line:
https://github.com/JimHokanson/plotBig_Matlab/blob/d6889bc0beccf9c24e85e168fce8185baf6fb7f7/%2Bbig_plot/compile.m#L24
I do not even see a `compilers` method of the `mex` class.

Using Matlab R2015b on Ubunu 14.04.

**Comment by JimHokanson** [comment]
I'm currently working on updating the documentation and code. The obvious option `big_plot.compile` is setup for experimental code that I'm working on. 

I just added support for Linux in a file called compile2.m

RIght now you need to highlight everything and execute it (I think because it is in a private folder and calling the name of the script doesn't get resolved even when in that directory)

Let me know if you have any questions and if it works or doesn't work. There are some flags at the beginning you can toggle. More documentation has been added to the docs folder in "how_to_compile.md"

I've also uploaded the appropriate binaries. I've thought about putting them online for optional download but right now they're in the repo itself.

**Comment by CsatiZoltan** [comment]
Still doesn't compile with GCC 4.8.4, even with
```
USE_OPENMP = 0; %use multiple threads
USE_SIMD = 0;   %make parallel within thread
```

The error message is:
```
Error using mex
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/same_diff_mex.c:5:1: error: expected identifier
or ‘(’ before ‘/’ token
 //  M-file gateway is:
 ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/same_diff_mex.c:10:1: error: expected
identifier or ‘(’ before ‘/’ token
 //  tic; wtf = big_plot.hasSameDiff(d); toc;
 ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/same_diff_mex.c:10:10: warning: data definition
has no type or storage class [enabled by default]
 //  tic; wtf = big_plot.hasSameDiff(d); toc;
          ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/same_diff_mex.c:10:16: error: ‘big_plot’
undeclared here (not in a function)
 //  tic; wtf = big_plot.hasSameDiff(d); toc;
                ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/same_diff_mex.c:10:37: error: ‘d’ undeclared
here (not in a function)
 //  tic; wtf = big_plot.hasSameDiff(d); toc;
                                     ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/same_diff_mex.c:10:41: warning: data definition
has no type or storage class [enabled by default]
 //  tic; wtf = big_plot.hasSameDiff(d); toc;
                                         ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/same_diff_mex.c:12:1: error: expected
identifier or ‘(’ before ‘/’ token
 //  Compile via:
 ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/same_diff_mex.c:22:37: error: invalid suffix
"d" on integer constant
     //      - data is assumed to be 1d (this could be verified ...)
                                     ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/same_diff_mex.c:75:27: warning: missing
terminating ' character [enabled by default]
     //sentinel block - don't need to worry about running past the end
                           ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/same_diff_mex.c:75:5: error: missing
terminating ' character
     //sentinel block - don't need to worry about running past the end
     ^
```

At least the binaries work. `big_plot.simdCheck` shows:
```
AVX HW supported
AVX OS supported
AVX2 HW supported
```

**Comment by JimHokanson** [comment]
Interesting. The errors are all from my `//` comments. Apparently that form of commenting is not supported until C99. For right now I put C11 flags in for `compile2.m`. I guess I could have used C99, maybe I'll change that eventually.

Please let me know if that fixes everything.

**Comment by CsatiZoltan** [comment]
No, it didn't. I will wait for your updated compilation method. Until then I use the provided mex files. Did you compile those ones with OpenMP or SIMD enabled?

By the way, this was the error message with the latest version of the master branch:
```
Error using mex
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/reduce_to_width_mex.c: In function
‘mexFunction’:
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/reduce_to_width_mex.c:591:18: error: expected
‘#pragma omp’ clause before ‘simd’
         PROCESS_EXTRA_NON_CHUNK_SAMPLES(double)
                  ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/reduce_to_width_mex.c:614:18: error: expected
‘#pragma omp’ clause before ‘simd’
         PROCESS_EXTRA_NON_CHUNK_SAMPLES(float)
                  ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/reduce_to_width_mex.c:632:18: error: expected
‘#pragma omp’ clause before ‘simd’
         PROCESS_EXTRA_NON_CHUNK_SAMPLES(uint64_t)
                  ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/reduce_to_width_mex.c:660:18: error: expected
‘#pragma omp’ clause before ‘simd’
         PROCESS_EXTRA_NON_CHUNK_SAMPLES(uint32_t)
                  ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/reduce_to_width_mex.c:688:18: error: expected
‘#pragma omp’ clause before ‘simd’
         PROCESS_EXTRA_NON_CHUNK_SAMPLES(uint16_t)
                  ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/reduce_to_width_mex.c:716:18: error: expected
‘#pragma omp’ clause before ‘simd’
         PROCESS_EXTRA_NON_CHUNK_SAMPLES(uint8_t)
                  ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/reduce_to_width_mex.c:732:18: error: expected
‘#pragma omp’ clause before ‘simd’
         PROCESS_EXTRA_NON_CHUNK_SAMPLES(int64_t)
                  ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/reduce_to_width_mex.c:760:18: error: expected
‘#pragma omp’ clause before ‘simd’
         PROCESS_EXTRA_NON_CHUNK_SAMPLES(int32_t)
                  ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/reduce_to_width_mex.c:788:18: error: expected
‘#pragma omp’ clause before ‘simd’
         PROCESS_EXTRA_NON_CHUNK_SAMPLES(int16_t)
                  ^
/home/zoli/Desktop/CutFEM-2/ext/plotBig_Matlab-master/+big_plot/private/reduce_to_width_mex.c:816:18: error: expected
‘#pragma omp’ clause before ‘simd’
         PROCESS_EXTRA_NON_CHUNK_SAMPLES(int8_t)
                  ^


Error in compile2 (line 100)
mex(options{:})
```

**Comment by JimHokanson** [comment]
I think I had both flags enabled.

Are you still getting the same error? I'll probably just go ahead and convert to multi-line comments.

**Comment by CsatiZoltan** [comment]
No, not the same. See my updated previous comment.

**Comment by JimHokanson** [comment]
Ah I see. Apparently you are using an old version of OpenMP which doesn't support the simd clause (I think). I'll need to add an extra check for older versions.

**Comment by JimHokanson** [comment]
@CsatiZoltan 

I was in the middle of working on making some fixes and I noticed you closed the issue. Did you make any changes to get things to work? Thanks.

**Comment by CsatiZoltan** [comment]
I looked for SIMD support in OpenMP and I [found](https://gcc.gnu.org/wiki/openmp) that OpenMP 4.0 is required for that, supported by GCC as of version 4.9. I have an older version (to maintain compatibility with Matlab). So currently, I am using your binaries.

> I'm currently working on updating the documentation and code. The obvious option big_plot.compile is setup for experimental code that I'm working on.

When the `compile` method is ready, I will reopen this issue and let you know if that works or not.

Your latest version compiles if I disable both OpenMP and SIMD. If I only disable SIMD, I get the same error as before.
![screenshot from 2018-06-12 08 56 59](https://user-images.githubusercontent.com/12742890/41274696-a4e1123c-6e1e-11e8-8a9b-bafca5c38267.png)

**Comment by JimHokanson** [comment]
Ah ok, that makes sense. Yeah, I just threw together the compiling script and technically there are three options for OPENMP, 1) no OPENMP, 2) OPENMP with compiler SIMD, and 3) OPENMP with no compiler SIMD. The SIMD flag option in my code is for my explicit SIMD code. 

The OpenMP with compiler SIMD  means that we allow the compiler to generate simd within OpenMP if it can.

Anyway, I'll add the extra OpenMP version checking and it should fix the problem.
